// This class represents a Habit object
// It is used as a model for storing and retrieving data from the database
class Habit {
  int? id; // Unique ID (auto-generated by database)
  String name; // Name of the habit
  String description; // Description of the habit
  int progress; // Progress value from 0 to 100

  // Constructor to create a Habit object
  Habit({
    this.id,
    required this.name,
    required this.description,
    this.progress = 0, // Default progress is 0
  });

  // Converts Habit object into a Map
  // This is required for inserting/updating data in SQLite
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'progress': progress,
    };
  }

  // Converts Map data from database into a Habit object
  // This is used when reading data from SQLite
  factory Habit.fromMap(Map<String, dynamic> map) {
    return Habit(
      id: map['id'],
      name: map['name'],
      description: map['description'],
      progress: map['progress'],
    );
  }
}